# Generated by Django 3.2.3 on 2021-05-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0002_post_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='This is da content'),
            preserve_default=False,
        ),
    ]
