# Generated by Django 3.2.3 on 2021-05-24 14:46

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communitymanager', '0003_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2021, 5, 24, 16, 46, 34, 332286)),
        ),
        migrations.AddField(
            model_name='post',
            name='date_event',
            field=models.DateField(default=datetime.datetime(2021, 5, 24, 16, 46, 34, 332286)),
        ),
        migrations.AddField(
            model_name='post',
            name='event',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
