# Generated by Django 3.2.3 on 2021-05-24 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0004_auto_20210524_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2021, 5, 24, 17, 43, 9, 390425)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_event',
            field=models.DateField(null=True),
        ),
    ]
