# Generated by Django 3.2.3 on 2021-05-24 15:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0005_auto_20210524_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2021, 5, 24, 15, 43, 58, 452727, tzinfo=utc)),
        ),
    ]
