# Generated by Django 3.2.3 on 2021-05-24 15:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0006_alter_post_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2021, 5, 24, 15, 45, 59, 752853, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_event',
            field=models.DateField(blank=True),
        ),
    ]
