# Generated by Django 3.2.3 on 2021-05-24 15:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0007_auto_20210524_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2021, 5, 24, 15, 47, 44, 709126, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_event',
            field=models.DateField(blank=True, null=True),
        ),
    ]
