# Generated by Django 3.2.3 on 2021-05-24 16:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0009_auto_20210524_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2021, 5, 24, 16, 51, 59, 591136, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2021, 5, 24, 16, 51, 59, 590140, tzinfo=utc)),
        ),
    ]
