# Generated by Django 3.2.3 on 2021-05-26 12:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0010_auto_20210524_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_creation']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='This is the new title', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2021, 5, 26, 12, 15, 32, 591973, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2021, 5, 26, 12, 15, 32, 591973, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(),
        ),
    ]
