# Generated by Django 3.2.3 on 2021-05-26 21:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0011_auto_20210526_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2021, 5, 26, 21, 11, 21, 332423, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2021, 5, 26, 21, 11, 21, 332423, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
